# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: DazedNConfused-
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Buenos_Aires
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: C++
          plugin_languages_limit: 10
          plugin_languages_skipped: CoverAO
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_notable: yes
          repositories_affiliations: owner, COLLABORATOR
          repositories_forks: yes
